#!/bin/bash
echo "press 1 to open nano"
echo "press 2 to open vi"
echo "press 3 to open links"
echo "press 4 to exit"
read c
case $c in
1 )
nano
;;
2 )
vi
;;
3 )
links
;;
4 )
exit 0
;;
* )
echo "wrong command"
esac 
