#!/bin/bash
>answer5.log
ppid=0
count=0
art=0
while read line
do
	ppid_tmp=$(echo "$line" | grep -Eo "Parent_ProcessID=[0-9]+" | grep -Eo "[0-9]+")
	art_tmp=$(echo "$line" | grep -Eo "[0-9]*\.{0,1}[0-9]+$")
	if (( $ppid != $ppid_tmp && $count != '0' )); then
		relation=$(echo "scale=7;$art/$count" | bc)
		echo "Average_Sleeping_Children_of_Parent=$ppid is $relation" >> answer5.log
		count=0
		art=0
	fi
	ppid=$ppid_tmp
	art=$(echo "scale=7;$art+$art_tmp" | bc)
	count=$(echo "scale=0;$count+1" 2>/dev/null | bc)
	echo $line >> answer5.log
	done < answer4.log
relation=$(echo "scale=7;$art/$count" | bc)
echo "Average_Sleeping_Children_of_Parent=$ppid is $relation" >> answer5.log

