#!/bin/bash
>answer4.log
tmp=$(ls /proc | grep -E "^[0-9]+")
for tmp_pid in $tmp
do
ppid_tmp=$(cat /proc/$tmp_pid/status 2>/dev/null | grep -E "PPid:" | grep -Eo "[0-9]+")
if [[ $ppid_tmp == "" ]]; then continue; fi
sum_tmp=$(cat /proc/$tmp_pid/sched | grep -E "sum_exec_runtime" | grep -Eo "[^[:space:]]+$")
nr_tmp=$(cat /proc/$tmp_pid/sched | grep -E "nr_switches" | grep -Eo "[^[:space:]]+$")
art_tmp=$(echo "scale=7;$sum_tmp/$nr_tmp" | bc)
echo "ProcessId=$tmp_pid : Parent_ProcessID=$ppid_tmp : Average_Running_Time=$art_tmp" >>\
\answer4.log
done
file_tmp=$(cat answer4.log | sort -t':' -nk2.19)
echo "$file_tmp" > answer4.log
