#!/bin/bash
tmp=$(ps -Ao "%u %p:%c" | grep -E "^user.*" | grep -Eo "[^[:space:]]+$")
if [[ $tmp == "" ]]
then
	echo "0" > answer1.log
else
	echo "$tmp" | wc -l > answer1.log
	echo "$tmp" >> answer1.log 
fi


