#!/bin/bash
tmp=$(date +%m-%d-%y_%H:%M:%S)
mkdir ~/test 2>/dev/null && {
	echo "catalog test was created succesfully" > ~/report
	touch ~/test/"$tmp"
}
ping 'www.net_nikogo' 2>/dev/null || {
	tmp=$(date +%m-%d-%y_%H:%M:%S)
	echo "$tmp Error" >> ~/report
}

